import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { map, shareReplay } from 'rxjs/operators';
import { Course } from 'models/course.model';

@Injectable({
  providedIn: 'root',
})
export class CourseService {
  DUMMY_COURSE_DATA: Course[] = [
    {
      units: 4,
      title: 'Foundations of Data Science',
      dept: 'COMPSCI',
      no: 'C8',
      id: 'compscic8',
      tags: [],
    },
    {
      units: 4,
      title: 'The Beauty and Joy of Computing',
      dept: 'COMPSCI',
      no: '10',
      id: 'compsci10',
      tags: [],
    },
    {
      units: 1,
      title: 'Freshman Seminars',
      dept: 'COMPSCI',
      no: '24',
      id: 'compsci24',
      tags: [],
    },
    {
      units: 1,
      title: 'Completion of Work in Computer Science 61A',
      dept: 'COMPSCI',
      no: '47A',
      id: 'compsci47a',
      tags: [],
    },
    {
      units: 1,
      title: 'Completion of Work in Computer Science 61B',
      dept: 'COMPSCI',
      no: '47B',
      id: 'compsci47b',
      tags: [],
    },
    {
      units: 1,
      title: 'Completion of Work in Computer Science 61C',
      dept: 'COMPSCI',
      no: '47C',
      id: 'compsci47c',
      tags: [],
    },
    {
      units: 4,
      title: 'The Structure and Interpretation of Computer Programs',
      dept: 'COMPSCI',
      no: '61A',
      id: 'compsci61a',
      tags: [],
    },
    {
      units: 4,
      title: 'Data Structures',
      dept: 'COMPSCI',
      no: '61B',
      id: 'compsci61b',
      tags: [],
    },
    {
      units: 4,
      title: 'Great Ideas of Computer Architecture (Machine Structures)',
      dept: 'COMPSCI',
      no: '61C',
      id: 'compsci61c',
      tags: [],
    },
    {
      units: 4,
      title: 'Discrete Mathematics and Probability Theory',
      dept: 'COMPSCI',
      no: '70',
      id: 'compsci70',
      tags: [],
    },
    {
      units: 3,
      title: 'Computational Structures in Data Science',
      dept: 'COMPSCI',
      no: '88',
      id: 'compsci88',
      tags: [],
    },
    {
      units: 4,
      title: 'Computer Architecture and Engineering',
      dept: 'COMPSCI',
      no: '152',
      id: 'compsci152',
      tags: ['eecs-upper-div'],
    },
    {
      units: 4,
      title: 'User Interface Design and Development',
      dept: 'COMPSCI',
      no: '160',
      id: 'compsci160',
      tags: ['eecs-upper-div'],
    },
    {
      units: 4,
      title: 'Computer Security',
      dept: 'COMPSCI',
      no: '161',
      id: 'compsci161',
      tags: ['eecs-upper-div'],
    },
    {
      units: 4,
      title: 'Operating Systems and System Programming',
      dept: 'COMPSCI',
      no: '162',
      id: 'compsci162',
      tags: ['eecs-upper-div'],
    },
    {
      units: 4,
      title: 'Introduction to the Internet: Architecture and Protocols',
      dept: 'COMPSCI',
      no: '168',
      id: 'compsci168',
      tags: ['eecs-upper-div'],
    },
    {
      units: 4,
      title: 'Efficient Algorithms and Intractable Problems',
      dept: 'COMPSCI',
      no: '170',
      id: 'compsci170',
      tags: ['eecs-upper-div'],
    },
    {
      units: 4,
      title: 'Designing, Visualizing and Understanding Deep Neural Networks',
      dept: 'COMPSCI',
      no: 'L182',
      id: 'compscil182',
      tags: ['eecs-upper-div'],
    },
    {
      units: 4,
      title: 'Designing, Visualizing and Understanding Deep Neural Networks',
      dept: 'COMPSCI',
      no: 'W182',
      id: 'compsciw182',
      tags: ['eecs-upper-div'],
    },
    {
      units: 4,
      title: 'Foundations of Computer Graphics',
      dept: 'COMPSCI',
      no: '184',
      id: 'compsci184',
      tags: ['eecs-upper-div'],
    },
    {
      units: 4,
      title: 'Introduction to Database Systems',
      dept: 'COMPSCI',
      no: 'W186',
      id: 'compsciw186',
      tags: ['eecs-upper-div'],
    },
    {
      units: 4,
      title: 'Introduction to Artificial Intelligence',
      dept: 'COMPSCI',
      no: '188',
      id: 'compsci188',
      tags: ['eecs-upper-div'],
    },
    {
      units: 4,
      title: 'Introduction to Machine Learning',
      dept: 'COMPSCI',
      no: '189',
      id: 'compsci189',
      tags: ['eecs-upper-div'],
    },
    {
      units: 3,
      title: 'Quantum Information Science and Technology',
      dept: 'COMPSCI',
      no: 'C191',
      id: 'compscic191',
      tags: ['eecs-upper-div'],
    },
    {
      units: 1,
      title: 'Special Topics',
      dept: 'COMPSCI',
      no: '194',
      id: 'compsci194',
      tags: ['eecs-upper-div'],
    },
    {
      units: 1,
      title: 'Social Implications of Computer Technology',
      dept: 'COMPSCI',
      no: '195',
      id: 'compsci195',
      tags: [],
    },
    {
      units: 1,
      title: 'Directed Group Studies for Advanced Undergraduates',
      dept: 'COMPSCI',
      no: '198',
      id: 'compsci198',
      tags: [],
    },
    {
      units: 4,
      title: 'Designing Information Devices and Systems I',
      dept: 'EECS',
      no: '16A',
      id: 'eecs16a',
      tags: [],
    },
    {
      units: 4,
      title: 'Designing Information Devices and Systems II',
      dept: 'EECS',
      no: '16B',
      id: 'eecs16b',
      tags: [],
    },
    {
      units: 4,
      title: 'Robotic Manipulation and Interaction',
      dept: 'EECS',
      no: 'C106B',
      id: 'eecsc106b',
      tags: ['eecs-upper-div'],
    },
    {
      units: 4,
      title: 'Probability and Random Processes',
      dept: 'EECS',
      no: '126',
      id: 'eecs126',
      tags: ['eecs-upper-div'],
    },
    {
      units: 4,
      title: 'Optimization Models in Engineering',
      dept: 'EECS',
      no: '127',
      id: 'eecs127',
      tags: ['eecs-upper-div'],
    },
    {
      units: 3,
      title: 'Introduction to Digital Design and Integrated Circuits',
      dept: 'EECS',
      no: '151',
      id: 'eecs151',
      tags: ['eecs-upper-div'],
    },
    {
      units: 2,
      title: 'Application Specific Integrated Circuits Laboratory',
      dept: 'EECS',
      no: '151LA',
      id: 'eecs151la',
      tags: ['eecs-upper-div'],
    },
    {
      units: 2,
      title: 'Field-Programmable Gate Array Laboratory',
      dept: 'EECS',
      no: '151LB',
      id: 'eecs151lb',
      tags: ['eecs-upper-div'],
    },
    {
      units: 4,
      title: 'Reading and Composition',
      dept: 'ENGLISH',
      no: 'R1A',
      id: 'englishr1a',
      tags: [],
    },
    {
      units: 4,
      title: 'Reading and Composition',
      dept: 'ENGLISH',
      no: 'R1B',
      id: 'englishr1b',
      tags: [],
    },
    {
      units: 4,
      title: 'First Humanities/Social Science',
      dept: 'H/SS',
      no: '1AC',
      id: 'hss1ac',
      tags: [],
    },
    {
      units: 4,
      title: 'Second Humanities/Social Science',
      dept: 'H/SS',
      no: '2',
      id: 'hss2',
      tags: [],
    },
    {
      units: 4,
      title: 'Third Humanities/Social Science',
      dept: 'H/SS',
      no: '100',
      id: 'hss100',
      tags: [],
    },
    {
      units: 4,
      title: 'Fourth Humanities/Social Science',
      dept: 'H/SS',
      no: '101',
      id: 'hss101',
      tags: [],
    },
    {
      units: 4,
      title: 'Calculus',
      dept: 'MATH',
      no: '1A',
      id: 'math1a',
      tags: [],
    },
    {
      units: 4,
      title: 'Calculus',
      dept: 'MATH',
      no: '1B',
      id: 'math1b',
      tags: [],
    },
    {
      units: 4,
      title: 'Multivariable Calculus',
      dept: 'MATH',
      no: '53',
      id: 'math53',
      tags: [],
    },
    {
      units: 4,
      title: 'Physics for Scientists and Engineers',
      dept: 'PHYSICS',
      no: '7A',
      id: 'physics7a',
      tags: [],
    },
    {
      units: 4,
      title: 'Physics for Scientists and Engineers',
      dept: 'PHYSICS',
      no: '7B',
      id: 'physics7b',
      tags: [],
    },
  ];

  private sharedCourseData: Observable<Course[]>;

  constructor() {}

  getCourses(): Observable<Course[]> {
    if (!this.sharedCourseData) {
      this.sharedCourseData = of(this.DUMMY_COURSE_DATA).pipe(
        map((rawCourses) => rawCourses.map((rawCourse) => new Course(rawCourse))),
        shareReplay()
      );
    }
    return this.sharedCourseData;
  }
}
