name: Angular CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install Dependencies
      run: cd client && npm ci
    - name: Build Angular App
      run: cd client && npm run build-dev
  lint-and-pretty:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install Dependencies
      run: cd client && npm ci
    - name: ESLint
      run: cd client && npm run lint
    - name: Prettier
      run: cd client && npm run pretty
