name: Angular CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: npm install
      run: npm ci
    - name: npm run build
      run: npm run build --prod
    - name: npm run test
      run: npm run test-ci
