name: Angular CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install Yarn
      run: npm install --global yarn
    - name: Install Dependencies
      run: cd client && yarn install --frozen-lockfile
    - name: Build Angular App
      run: cd client && yarn build-dev
  lint-and-pretty:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install Yarn
      run: npm install --global yarn
    - name: Install Dependencies
      run: cd client && yarn install --frozen-lockfile
    - name: ESLint
      run: cd client && yarn lint
    - name: Prettier
      run: cd client && yarn pretty
