name: Angular CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: cd client && npm ci
    - name: Build Angular App
      run: cd client && npm run build
  lint-and-pretty:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: cd client && npm install
    - name: ESLint
      run: cd client && npm run lint
    - name: Prettier
      run: cd client && npm run pretty
