name: Heroku CD - Development

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install Dependencies
      run: npm ci
    - name: Build
      run: npm run build-dev
    - name: Deploy to Heroku
      run: |
        cd server &&
        git init &&
        git add -A &&
        git commit -m 'Deploy' &&
        git push -f https://git:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/gradtrak-dev.git master
      env:
        GIT_AUTHOR_NAME: GitHub Action
        GIT_AUTHOR_EMAIL: gradtrak@example.com
        GIT_COMMITTER_NAME: GitHub Action
        GIT_COMMITTER_EMAIL: gradtrak@example.com
