name: Development CD

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install Yarn
      run: npm install --global yarn
    - name: Install Dependencies
      run: (cd client && yarn install --frozen-lockfile) && (cd server && yarn install --frozen-lockfile)
    - name: Build
      run: yarn build-dev
    - name: Deploy to Heroku
      run: |
        cd server &&
        rm -rf .git &&
        git init &&
        git add -A &&
        git commit -m 'Deploy' &&
        git push -f https://git:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/gradtrak-dev.git master
      env:
        GIT_AUTHOR_NAME: GitHub Action
        GIT_AUTHOR_EMAIL: info@gradtrak.me
        GIT_COMMITTER_NAME: GitHub Action
        GIT_COMMITTER_EMAIL: info@gradtrak.me
